### ISSUE TITLE
Slate build errors when no config.yml file

### ISSUE THREAD

**Issue by cshold** [Shopify/slate-tools#45]
Technically you shouldn't need a `config.yml` to do a local task like build. If you do you get this ugly output even though the task works as expected.

```
Message:
    `config.yml` does not exist. You need to add a config file before you can upload your theme to Shopify.
Stack:
Error: `config.yml` does not exist. You need to add a config file before you can upload your theme to Shopify.
    at processConfig (/Users/carsonshold/Documents/Projects/slate/node_modules/@shopify/slate-tools/lib/tasks/build-config.js:18:11)
    at Gulp.gulp.task (/Users/carsonshold/Documents/Projects/slate/node_modules/@shopify/slate-tools/lib/tasks/build-config.js:37:10)
    at module.exports (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:214:10)
    at /Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:279:18
    at finish (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:214:10)
    at /Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:279:18
    at finish (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/carsonshold/Documents/Projects/slate/node_modules/orchestrator/index.js:134:8)
```

### Why should this be fixed?

I'm writing up some Slate usage docs that suggest running `slate build` before the steps of creating an app and config file. Quicker to see it work = more trust in the tool (or so is my thinking).

If we can remove that error from `build` we're golden. 

cc @Shopify/themes-fed 
@macdonaldr93 @m-ux

**Comment by NathanPJF** [comment]
Possibly related: https://github.com/Shopify/slate-cli/issues/118
